apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx
        image: REPLACE_IMAGE
        env:
        - name: ENV_MESSAGE
          value: "Hello from Prod!"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prod
spec:
  type: LoadBalancer
  selector:
    app: nginx-prod
  ports:
  - port: 80
    targetPort: 80
