name: CI-CD to GKE

on:
  push:
    branches:
      - staging
      - main
      - prod

env:
  PROJECT_ID: sanguine-rhythm-477418-t9
  REGION: us-east4
  REPO: nginx-gke-repo
  CLUSTER: nginx-gke-cicd
  USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Auth to GCP
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    # Install gcloud + plugin
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Install GKE auth plugin
      run: gcloud components install gke-gcloud-auth-plugin --quiet

    # Docker login
    - name: Configure Docker auth
      run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    # Build + tag image
    - name: Build image
      run: |
        IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/nginx:${GITHUB_SHA:0:7}"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        docker build -t $IMAGE ./app

    # Push image
    - name: Push image
      run: docker push $IMAGE

    # Connect to GKE
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER \
          --region $REGION

    # Deploy to Staging
    - name: Deploy to Staging
      if: github.ref == 'refs/heads/staging'
      run: |
        kubectl apply -f k8s/namespaces/staging.yaml
        sed "s|REPLACE_IMAGE|$IMAGE|" k8s/staging.yaml | kubectl apply -f -
        kubectl -n staging rollout status deploy/nginx-staging --timeout=90s

    # Deploy to Prod (for BOTH main and prod branch)
    - name: Deploy to Prod
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod'
      run: |
        kubectl apply -f k8s/namespaces/prod.yaml
        sed "s|REPLACE_IMAGE|$IMAGE|" k8s/prod.yaml | kubectl apply -f -
        kubectl -n prod rollout status deploy/nginx-prod --timeout=120s
